name: Deploy Backend on Test Success

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: python3.10 -m pip install -r requirements.txt

    - name: Run tests
      run: python3.10 ./x.py test --args="-n 6"
      env: 
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}