name: Deploy Backend on Test Success

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: python3.10 -m pip install -r requirements.txt

    - name: Run tests
      run: python3.10 ./x.py test
      env: 
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

  deploy:
    needs: test-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add additional steps to test/build your code here

      - name: Fetch Jenkins CSRF crumb and trigger Jenkins job
        run: |
          # Fetch the CSRF crumb from Jenkins
          crumb=$(curl -s "${{ secrets.JENKINS_URL }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)" -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}")
          echo "Crumb fetched: $crumb"
          
          # Trigger the Jenkins job
          curl -X POST "${{ secrets.JENKINS_URL }}/job/itxBackend/build" \
          -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
          -H "$crumb" \
          -H "Content-Type:application/x-www-form-urlencoded"
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}